/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fgc_kano.ui.views;

import fgc_kano.beansfiles.DatabaseException;
import fgc_kano.beansfiles.StudentDatabaseAccess;
import fgc_kano.beansfiles.StundentAllocationEntry;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author fr33wayz
 */
public class AllocationUI extends javax.swing.JPanel {

    /**
     * Creates new form AllocationUI
     */
    public AllocationUI() {
        initComponents();
        
        student = new StundentAllocationEntry();
        try {
            databaseAccess = new StudentDatabaseAccess();
            
        } catch (Exception error) {
            System.out.println(error.getMessage());
            
        }
        
    }
    
    public void showAllocationForm() {
        form = new JFrame("FGC UPDATE HOSTEL PROFILE");
        form.getContentPane().add(this);
        form.pack();
        form.setResizable(false);
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        form.setVisible(true);
        
    }
    
    private JFrame form;
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        ImageIcon icon = new ImageIcon(getClass().getResource("/fgc_kano/resources/newbg.jpg"));
        Image image = icon.getImage();
        if (image != null) {
            g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img_chooser = new javax.swing.JFileChooser();
        ui_std_profile = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_sn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_fn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_ot = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmb_state = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmb_religion = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cmb_sex = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_std_add = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        txt_tel_no = new javax.swing.JFormattedTextField();
        txt_lga = new javax.swing.JTextField();
        txt_dob = new datechooser.beans.DateChooserCombo();
        panel_hostel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cmb_hostel_type = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cmb_hostel_name = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        cmb_floor_no = new javax.swing.JComboBox();
        panel_image = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        btn_image = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txt_adm_no = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cmb_level = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        cmb_class = new javax.swing.JComboBox();
        panel_gurdian = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txt_gurdian_name = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_gurdian_tel_no = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_address_gurdian = new javax.swing.JTextField();
        panel_navg = new javax.swing.JPanel();
        btn_allocate = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        btn_adminpanel = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        img_chooser.setToolTipText("Pick an image");

        ui_std_profile.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Californian FB", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        ui_std_profile.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setText("SURNAME");

        txt_sn.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("FIRSTNAME");

        txt_fn.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setText("OTHER NAME");

        txt_ot.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("D-O-B");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("STATE");

        cmb_state.setBackground(new java.awt.Color(153, 153, 0));
        cmb_state.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "    Anambra", "    Enugu", "    Akwa Ibom", "    Adamawa", "    Abia", "    Bauchi", "    Bayelsa", "    Benue", "    Borno", "    Cross River", "    Delta", "    Ebonyi", "    Edo", "    Ekiti", "    Gombe", "    Imo", "    Jigawa", "    Kaduna", "    Kano", "    Katsina", "    Kebbi", "    Kogi", "    Kwara", "    Lagos", "    Nasarawa", "    Niger", "    Ogun", "    Ondo", "    Osun", "    Oyo", "    Plateau", "    Rivers", "    Sokoto", "    Taraba", "    Yobe", "    Zamfara" }));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setText("L.G.A");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setText("RELIGION");

        cmb_religion.setBackground(new java.awt.Color(153, 153, 0));
        cmb_religion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islam", "Christianity", "Traditionalist" }));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setText("SEX");

        cmb_sex.setBackground(new java.awt.Color(153, 153, 0));
        cmb_sex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel9.setText("ADDRESS");

        txt_std_add.setBackground(new java.awt.Color(255, 255, 204));
        txt_std_add.setColumns(20);
        txt_std_add.setLineWrap(true);
        txt_std_add.setRows(5);
        jScrollPane1.setViewportView(txt_std_add);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setText("TEL NO");

        txt_tel_no.setBackground(new java.awt.Color(255, 255, 204));
        txt_tel_no.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_lga.setBackground(new java.awt.Color(255, 255, 204));

        txt_dob.setCurrentView(new datechooser.view.appearance.AppearancesList("Bordered",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    txt_dob.setCalendarBackground(new java.awt.Color(255, 255, 153));
    txt_dob.setCalendarPreferredSize(new java.awt.Dimension(200, 180));
    txt_dob.setFieldFont(new java.awt.Font("Times New Roman", java.awt.Font.PLAIN, 12));
    txt_dob.setLocale(new java.util.Locale("en", "", ""));

    javax.swing.GroupLayout ui_std_profileLayout = new javax.swing.GroupLayout(ui_std_profile);
    ui_std_profile.setLayout(ui_std_profileLayout);
    ui_std_profileLayout.setHorizontalGroup(
        ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(ui_std_profileLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1)
                .addComponent(jLabel4)
                .addComponent(jLabel7)
                .addComponent(jLabel8)
                .addComponent(jLabel10))
            .addGap(18, 18, 18)
            .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tel_no, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_sn)
                        .addComponent(cmb_religion, 0, 155, Short.MAX_VALUE)
                        .addComponent(cmb_sex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(txt_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(53, 53, 53)
            .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ui_std_profileLayout.createSequentialGroup()
                    .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5))
                    .addGap(18, 18, 18)
                    .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmb_state, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_fn, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                    .addGap(40, 40, 40)
                    .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6))
                    .addGap(18, 18, 18)
                    .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_ot, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addComponent(txt_lga)))
                .addGroup(ui_std_profileLayout.createSequentialGroup()
                    .addComponent(jLabel9)
                    .addGap(44, 44, 44)
                    .addComponent(jScrollPane1)))
            .addContainerGap())
    );
    ui_std_profileLayout.setVerticalGroup(
        ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(ui_std_profileLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(txt_sn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(txt_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3)
                .addComponent(txt_ot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(25, 25, 25)
            .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(cmb_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_lga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(txt_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(ui_std_profileLayout.createSequentialGroup()
                    .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ui_std_profileLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(cmb_religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(ui_std_profileLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel9)))
                    .addGap(23, 23, 23)
                    .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(cmb_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ui_std_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txt_tel_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(ui_std_profileLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    panel_hostel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hostel Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Californian FB", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
    panel_hostel.setOpaque(false);

    jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    jLabel11.setText("HOSTEL TYPE");

    cmb_hostel_type.setBackground(new java.awt.Color(153, 153, 0));
    cmb_hostel_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male Hostel", "Female Hostel" }));

    jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    jLabel12.setText("HOSTEL NAME");

    cmb_hostel_name.setBackground(new java.awt.Color(153, 153, 0));
    cmb_hostel_name.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BOYS HOSTEL", "Benue Hostel", "Niger Hostel", "Rima Hostel", "Watari Hostel", "GIRLS HOSTEL", "Morem Hostel", "Amina Hostel", "Emotan Hostel" }));

    jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    jLabel13.setText("FLOOR");

    cmb_floor_no.setBackground(new java.awt.Color(153, 153, 0));
    cmb_floor_no.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Floor 1", "Floor 2", "Floor 3" }));

    javax.swing.GroupLayout panel_hostelLayout = new javax.swing.GroupLayout(panel_hostel);
    panel_hostel.setLayout(panel_hostelLayout);
    panel_hostelLayout.setHorizontalGroup(
        panel_hostelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_hostelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panel_hostelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel12)
                .addComponent(jLabel11)
                .addComponent(jLabel13))
            .addGap(18, 18, 18)
            .addGroup(panel_hostelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(cmb_hostel_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmb_hostel_name, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmb_floor_no, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(28, Short.MAX_VALUE))
    );
    panel_hostelLayout.setVerticalGroup(
        panel_hostelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_hostelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panel_hostelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(cmb_hostel_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(panel_hostelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(cmb_hostel_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
            .addGroup(panel_hostelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13)
                .addComponent(cmb_floor_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    panel_image.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Passport Size Must be 180x200", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
    panel_image.setOpaque(false);

    image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgc_kano/resources/ic_action_person.png"))); // NOI18N
    image.setToolTipText("");

    btn_image.setBackground(new java.awt.Color(0, 255, 0));
    btn_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgc_kano/resources/ic_action_camera_1.png"))); // NOI18N
    btn_image.setToolTipText("Upload  passwport from file");
    btn_image.setBorderPainted(false);
    btn_image.setFocusPainted(false);
    btn_image.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btn_image.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    btn_image.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_imageActionPerformed(evt);
        }
    });

    jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    jLabel17.setText("ADM-NO");

    txt_adm_no.setBackground(new java.awt.Color(255, 255, 153));

    jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    jLabel18.setText("LEVEL");

    cmb_level.setBackground(new java.awt.Color(153, 153, 0));
    cmb_level.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JSS1", "JSS2", "JSS3", "SS1", "SS2", "SS3" }));

    jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    jLabel19.setText("CLASS");

    cmb_class.setBackground(new java.awt.Color(153, 153, 0));
    cmb_class.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "F" }));

    javax.swing.GroupLayout panel_imageLayout = new javax.swing.GroupLayout(panel_image);
    panel_image.setLayout(panel_imageLayout);
    panel_imageLayout.setHorizontalGroup(
        panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_imageLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_imageLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel19))
                    .addGap(18, 18, 18)
                    .addGroup(panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_adm_no)
                        .addComponent(cmb_level, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmb_class, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(12, 12, 12))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_imageLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_image)
                    .addContainerGap())))
    );
    panel_imageLayout.setVerticalGroup(
        panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_imageLayout.createSequentialGroup()
            .addGroup(panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_imageLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_imageLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txt_adm_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(19, 19, 19)
                    .addGroup(panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(cmb_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(cmb_class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(31, 31, 31)
                    .addComponent(btn_image, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    panel_gurdian.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gurdian Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Californian FB", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
    panel_gurdian.setOpaque(false);

    jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    jLabel14.setText("GURDIAN NAME");

    txt_gurdian_name.setBackground(new java.awt.Color(255, 255, 153));

    jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    jLabel15.setText("TEL NO");

    txt_gurdian_tel_no.setBackground(new java.awt.Color(255, 255, 153));

    jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    jLabel16.setText("ADDRESS");

    txt_address_gurdian.setBackground(new java.awt.Color(255, 255, 153));

    javax.swing.GroupLayout panel_gurdianLayout = new javax.swing.GroupLayout(panel_gurdian);
    panel_gurdian.setLayout(panel_gurdianLayout);
    panel_gurdianLayout.setHorizontalGroup(
        panel_gurdianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_gurdianLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panel_gurdianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_gurdianLayout.createSequentialGroup()
                    .addGroup(panel_gurdianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15))
                    .addGap(18, 18, 18)
                    .addGroup(panel_gurdianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_gurdian_name)
                        .addComponent(txt_gurdian_tel_no)))
                .addGroup(panel_gurdianLayout.createSequentialGroup()
                    .addComponent(jLabel16)
                    .addGap(18, 18, 18)
                    .addComponent(txt_address_gurdian)))
            .addContainerGap())
    );
    panel_gurdianLayout.setVerticalGroup(
        panel_gurdianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_gurdianLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panel_gurdianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel14)
                .addComponent(txt_gurdian_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(panel_gurdianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel15)
                .addComponent(txt_gurdian_tel_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_gurdianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_gurdianLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jLabel16)
                    .addContainerGap())
                .addGroup(panel_gurdianLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(txt_address_gurdian, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))))
    );

    panel_navg.setOpaque(false);

    btn_allocate.setBackground(new java.awt.Color(0, 255, 0));
    btn_allocate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgc_kano/resources/ic_action_accept.png"))); // NOI18N
    btn_allocate.setText("Allocate ");
    btn_allocate.setToolTipText("Allocate Hostel");
    btn_allocate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btn_allocate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btn_allocate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_allocateActionPerformed(evt);
        }
    });

    btn_print.setBackground(new java.awt.Color(0, 255, 0));
    btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgc_kano/resources/printButton.png"))); // NOI18N
    btn_print.setMnemonic('P');
    btn_print.setText("Print");
    btn_print.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btn_print.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btn_print.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_printActionPerformed(evt);
        }
    });

    btn_adminpanel.setBackground(new java.awt.Color(0, 255, 0));
    btn_adminpanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgc_kano/resources/admin_btn.png"))); // NOI18N
    btn_adminpanel.setMnemonic('G');
    btn_adminpanel.setText("Admin");
    btn_adminpanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btn_adminpanel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btn_adminpanel.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_adminpanelActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout panel_navgLayout = new javax.swing.GroupLayout(panel_navg);
    panel_navg.setLayout(panel_navgLayout);
    panel_navgLayout.setHorizontalGroup(
        panel_navgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_navgLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_allocate, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btn_adminpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26))
    );
    panel_navgLayout.setVerticalGroup(
        panel_navgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_navgLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panel_navgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(btn_adminpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_print, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_allocate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(0, 0, Short.MAX_VALUE))
    );

    jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgc_kano/resources/AllocationForm.png"))); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(ui_std_profile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panel_hostel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_gurdian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addComponent(panel_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_navg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ui_std_profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panel_hostel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(panel_gurdian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panel_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_navg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_printActionPerformed
    {//GEN-HEADEREND:event_btn_printActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_adminpanelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_adminpanelActionPerformed
    {//GEN-HEADEREND:event_btn_adminpanelActionPerformed
        // TODO add your handling code here:
        form.setVisible(false);
        new AdminUIPanel().makeVisible();
    }//GEN-LAST:event_btn_adminpanelActionPerformed

    private void btn_allocateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_allocateActionPerformed
        // TODO add your handling code here:
        try {
            boolean inserted = databaseAccess.allocateStudent(allocate());
            if (inserted == true) {
                JOptionPane.showMessageDialog(this, "Mr/Mrs" + student.getS_name() + " has been Allocated"
                        + "\nHoste Successfully!!!");
            } else {
                JOptionPane.showMessageDialog(this, "Some Error While Allocating");
            }

//            resetComponent();
        } catch (DatabaseException de) {
            de.printStackTrace();
        }

    }//GEN-LAST:event_btn_allocateActionPerformed
    
    private ImageIcon icon;
    private void btn_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imageActionPerformed
        // TODO add your handling code here:
        img_chooser.showOpenDialog(getParent());
        File f = img_chooser.getSelectedFile();
        student.setPath(f.getAbsolutePath());
        icon = new ImageIcon(student.getPath());
        student.setIcon(icon);
        
        this.image.setIcon(student.getIcon());
        

    }//GEN-LAST:event_btn_imageActionPerformed
    
    private StudentDatabaseAccess databaseAccess;
    private StundentAllocationEntry student;
    private FileInputStream fis = null;
    
    private StundentAllocationEntry allocate() {
        
        File f = new File(student.getPath());
        try {
            fis = new FileInputStream(f);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Passport Uplaod Error", "No Image Selected",
                    JOptionPane.ERROR_MESSAGE);
        }
        Calendar calender = txt_dob.getSelectedDate();
        String date
                = String.valueOf(calender.get(Calendar.YEAR))
                + "-" + String.valueOf(calender.get(Calendar.MONTH) + 1) + "-"
                + String.valueOf(calender.get(Calendar.DAY_OF_MONTH));
        
        student.setAdmission_no(txt_adm_no.getText());
        student.setF_name(txt_fn.getText());
        student.setS_name(txt_sn.getText());
        student.setO_name(txt_ot.getText());
        student.setDob(date);
        student.setState((String) cmb_state.getSelectedItem());
        student.setLga(txt_lga.getText());
        student.setReligion((String) cmb_religion.getSelectedItem());
        student.setAddress(txt_std_add.getText());
        student.setSex((String) cmb_sex.getSelectedItem());
        student.setTel_no(txt_tel_no.getText());
        
        student.setHostel_name((String) cmb_hostel_name.getSelectedItem());
        student.setHostel_type((String) cmb_hostel_type.getSelectedItem());
        student.setFloor_number((String) cmb_floor_no.getSelectedItem());
        
        student.setGuardian_name(txt_gurdian_name.getText());
        student.setGuardian_add(txt_address_gurdian.getText());
        student.setGuadian_tel_no(txt_gurdian_tel_no.getText());
        
        student.setStd_class((String) cmb_class.getSelectedItem());
        student.setStd_lvl((String) cmb_level.getSelectedItem());
        student.setFis(fis);
        student.setFile(f);
        
        return student;
    }
    
    void resetComponent() {
        txt_address_gurdian.setText("");
        txt_adm_no.setText("");
        txt_fn.setText("");
        txt_gurdian_name.setText("");
        txt_gurdian_tel_no.setText("");
        txt_lga.setText("");
        txt_dob.setText("");
        txt_ot.setText(" ");
        txt_sn.setText(" ");
        txt_std_add.setText(" ");
        txt_tel_no.setText("");
        cmb_class.setSelectedIndex(0);
        cmb_floor_no.setSelectedIndex(0);
        cmb_hostel_name.setSelectedIndex(0);
        cmb_hostel_type.setSelectedIndex(0);
        cmb_level.setSelectedIndex(0);
        cmb_religion.setSelectedIndex(0);
        cmb_sex.setSelectedIndex(0);
        cmb_state.setSelectedIndex(0);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adminpanel;
    private javax.swing.JButton btn_allocate;
    private javax.swing.JButton btn_image;
    private javax.swing.JButton btn_print;
    private javax.swing.JComboBox cmb_class;
    private javax.swing.JComboBox cmb_floor_no;
    private javax.swing.JComboBox cmb_hostel_name;
    private javax.swing.JComboBox cmb_hostel_type;
    private javax.swing.JComboBox cmb_level;
    private javax.swing.JComboBox cmb_religion;
    private javax.swing.JComboBox cmb_sex;
    private javax.swing.JComboBox cmb_state;
    private javax.swing.JLabel image;
    private javax.swing.JFileChooser img_chooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_gurdian;
    private javax.swing.JPanel panel_hostel;
    private javax.swing.JPanel panel_image;
    private javax.swing.JPanel panel_navg;
    private javax.swing.JTextField txt_address_gurdian;
    private javax.swing.JTextField txt_adm_no;
    private datechooser.beans.DateChooserCombo txt_dob;
    private javax.swing.JTextField txt_fn;
    private javax.swing.JTextField txt_gurdian_name;
    private javax.swing.JTextField txt_gurdian_tel_no;
    private javax.swing.JTextField txt_lga;
    private javax.swing.JTextField txt_ot;
    private javax.swing.JTextField txt_sn;
    private javax.swing.JTextArea txt_std_add;
    private javax.swing.JFormattedTextField txt_tel_no;
    private javax.swing.JPanel ui_std_profile;
    // End of variables declaration//GEN-END:variables
}
