/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fgc_kano.ui.views;

import fgc_kano.beansfiles.MySQLAdapter;
import fgc_kano.beansfiles.TableSorter;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.print.PrinterException;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class ReportWizard extends javax.swing.JPanel {

    /**
     * Creates new form ReportWizard
     */
    public ReportWizard() {
        initComponents();
    }

    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        ImageIcon icon = new ImageIcon(getClass().getResource("/fgc_kano/resources/Report_bg.jpg"));
        Image image = icon.getImage();
        if (image != null) {
            g.drawImage(image, 0, 0, getWidth(), getHeight(), this);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group = new javax.swing.ButtonGroup();
        report_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        model = new DefaultListModel<String>();

        db_adabter = new  MySQLAdapter();
        sorter = new TableSorter();
        result_table = new javax.swing.JTable(sorter);
        btn_holders = new javax.swing.JPanel();
        girls_hostel = new javax.swing.JCheckBox();
        boys_hostel = new javax.swing.JCheckBox();
        all_hostel = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        hostel_list = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_gen_rep = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        btn_admin = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        report_panel.setBackground(new java.awt.Color(255, 51, 0));
        report_panel.setOpaque(false);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setOpaque(true);

        sorter.addMouseListenerToHeaderInTable(result_table);
        result_table.setModel(db_adabter);
        result_table.setOpaque(false);
        result_table.setShowHorizontalLines(true);
        result_table.setShowVerticalLines(true);
        jScrollPane2.setViewportView(result_table);

        javax.swing.GroupLayout report_panelLayout = new javax.swing.GroupLayout(report_panel);
        report_panel.setLayout(report_panelLayout);
        report_panelLayout.setHorizontalGroup(
            report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        report_panelLayout.setVerticalGroup(
            report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_holders.setBackground(new java.awt.Color(0, 255, 0));
        btn_holders.setOpaque(false);

        btn_group.add(girls_hostel);
        girls_hostel.setText("GIRLS HOSTEL");
        girls_hostel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girls_hostelActionPerformed(evt);
            }
        });

        btn_group.add(boys_hostel);
        boys_hostel.setText("BOYS HOSTEL");
        boys_hostel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boys_hostelActionPerformed(evt);
            }
        });

        btn_group.add(all_hostel);
        all_hostel.setText("ALL HOSTEL");
        all_hostel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_hostelActionPerformed(evt);
            }
        });

        hostel_list.setModel(model);
        hostel_list.setModel(model);
        hostel_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(hostel_list);

        javax.swing.GroupLayout btn_holdersLayout = new javax.swing.GroupLayout(btn_holders);
        btn_holders.setLayout(btn_holdersLayout);
        btn_holdersLayout.setHorizontalGroup(
            btn_holdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_holdersLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(btn_holdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(girls_hostel)
                    .addComponent(boys_hostel)
                    .addComponent(all_hostel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_holdersLayout.setVerticalGroup(
            btn_holdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_holdersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_holdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btn_holdersLayout.createSequentialGroup()
                        .addComponent(girls_hostel)
                        .addGap(18, 18, 18)
                        .addComponent(boys_hostel)
                        .addGap(18, 18, 18)
                        .addComponent(all_hostel)))
                .addGap(89, 89, 89))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgc_kano/resources/ReportLogo.png"))); // NOI18N

        jPanel1.setOpaque(false);

        btn_gen_rep.setBackground(new java.awt.Color(0, 204, 0));
        btn_gen_rep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgc_kano/resources/query_report.png"))); // NOI18N
        btn_gen_rep.setText("Generate");
        btn_gen_rep.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_gen_rep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_gen_rep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gen_repActionPerformed(evt);
            }
        });

        btn_print.setBackground(new java.awt.Color(0, 204, 0));
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgc_kano/resources/print_report_btn.png"))); // NOI18N
        btn_print.setText("Print");
        btn_print.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_print.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_admin.setBackground(new java.awt.Color(0, 255, 0));
        btn_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgc_kano/resources/report_admin.png"))); // NOI18N
        btn_admin.setText("Admin");
        btn_admin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_admin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_print)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_gen_rep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_admin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_gen_rep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(report_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_holders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_holders, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(report_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gen_repActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gen_repActionPerformed
        // TODO add your handling code here:

        if (girls_hostel.isSelected() || boys_hostel.isSelected()) {
            getBox();
        } else {
            db_adabter.executeQuery(sql_all_hostel);
        }

    }//GEN-LAST:event_btn_gen_repActionPerformed

    
    void getBox() {
        String current_selection = (String) hostel_list.getSelectedValue();

        String query = "";
        switch (current_selection) {
            case "All Girls":
                query = sql_girls;
                break;
            case "Morem Hostel":
                query = sql_morem;
                break;
            case "Niger Hostel":
                query = sql_niger_hostel;
                break;
            case "Benue Hostel":
                query = sql_benue_hostel;
                break;
            case "Amina Hostel":
                query = sql_amina_hostel;
                break;
            case "Rima Hostel":
                query = sql_rima_hostel;
                break;
            case "Watari Hostel":
                query = sql_watari_hostel;
                break;
            case "All Boys":
                query = sql_boys;
                break;

            default:
                System.out.println("Bad Selection");

        }

        db_adabter.executeQuery(query);
    }
    private void girls_hostelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girls_hostelActionPerformed
        // TODO add your handling code here:
        model.removeAllElements();
        for (int s = 0; s < girl_hostel.length; s++) {
            model.add(s, girl_hostel[s]);
        }

        hostel_list.revalidate();
    }//GEN-LAST:event_girls_hostelActionPerformed

    private void boys_hostelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boys_hostelActionPerformed
        // TODO add your handling code here:
        model.removeAllElements();
        for (int s = 0; s < boy_hostel.length; s++) {
            model.add(s, boy_hostel[s]);
        }

        hostel_list.revalidate();
    }//GEN-LAST:event_boys_hostelActionPerformed

    private void all_hostelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_hostelActionPerformed
        // TODO add your handling code here:
        model.removeAllElements();
        hostel_list.revalidate();
    }//GEN-LAST:event_all_hostelActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        try {
            // TODO add your handling code here:
            result_table.print();
        } catch (PrinterException printerException) {
            JOptionPane.showMessageDialog(null, "Printing Error", "There was an Error!!! Sending to Printer", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed
        // TODO add your handling code here:
        form.setVisible(false);
        new AdminUIPanel().makeVisible();
    }//GEN-LAST:event_btn_adminActionPerformed

    public void showReportForm() {
        form = new JFrame("FGC GENERATE REPORT");
        form.getContentPane().add(this);
        form.pack();
        form.setResizable(false);
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        form.setVisible(true);

    }
    private JFrame form;
    private String[] boy_hostel = {"All Boys", "Benue Hostel", "Niger Hostel", "Rima Hostel", "Watari Hostel"},
            girl_hostel = {"All Girls", "Morem Hostel", "Amina Hostel", "Emotan Hostel"};

    private String sql_all_hostel = "SELECT \n"
            + "std_id, student_profile.admission_no, surname, firstname, othername, \n"
            + "dob, sex,class_profile.level,class, religion, hostel_name, floor_no, \n"
            + "guardian_name \n"
            + "from \n"
            + "student_profile, hostel_profile, class_profile, guardian_profile\n"
            + "where student_profile.admission_no = class_profile.admission_no\n"
            + "and student_profile.admission_no = hostel_profile.admission_no\n"
            + "and student_profile.admission_no = guardian_profile.admission_no\n",
            sql_girls = "SELECT \n"
            + "std_id, student_profile.admission_no, surname, firstname, othername, \n"
            + "dob, sex,class_profile.level,class, religion, hostel_name, floor_no, \n"
            + "guardian_name \n"
            + "from \n"
            + "student_profile, hostel_profile, class_profile, guardian_profile\n"
            + "where student_profile.admission_no = class_profile.admission_no\n"
            + "and student_profile.admission_no = hostel_profile.admission_no\n"
            + "and student_profile.admission_no = guardian_profile.admission_no\n"
            + "and hostel_type  = \"Female Hostel\" ",
            sql_boys = "SELECT \n"
            + "std_id, student_profile.admission_no, surname, firstname, othername, \n"
            + "dob, sex,class_profile.level,class, religion, hostel_name, floor_no, \n"
            + "guardian_name \n"
            + "from \n"
            + "student_profile, hostel_profile, class_profile, guardian_profile\n"
            + "where student_profile.admission_no = class_profile.admission_no\n"
            + "and student_profile.admission_no = hostel_profile.admission_no\n"
            + "and student_profile.admission_no = guardian_profile.admission_no\n"
            + "and hostel_type = \"Male Hostel\"",
            sql_morem = " SELECT \n"
            + "std_id, student_profile.admission_no, surname, firstname, othername, \n"
            + "dob, sex,class_profile.level,class, religion, hostel_name, floor_no, \n"
            + "guardian_name \n"
            + "from \n"
            + "student_profile, hostel_profile, class_profile, guardian_profile\n"
            + "where student_profile.admission_no = class_profile.admission_no\n"
            + "and student_profile.admission_no = hostel_profile.admission_no\n"
            + "and student_profile.admission_no = guardian_profile.admission_no\n"
            + "and hostel_profile.hostel_name = \"Morem Hostel\"",
            sql_niger_hostel = "SELECT std_id, student_profile.admission_no, surname, firstname, othername, \n"
            + "dob, sex,class_profile.level,class, religion, hostel_name, floor_no, \n"
            + "guardian_name from student_profile, hostel_profile, class_profile, guardian_profile\n"
            + "where student_profile.admission_no = class_profile.admission_no\n"
            + "and student_profile.admission_no = hostel_profile.admission_no\n"
            + "and student_profile.admission_no = guardian_profile.admission_no\n"
            + "and hostel_profile.hostel_name = \"Niger Hostel\"",
            sql_benue_hostel = "SELECT std_id, student_profile.admission_no, surname, firstname, othername, \n"
            + "dob, sex,class_profile.level,class, religion, hostel_name, floor_no, \n"
            + "guardian_name from student_profile, hostel_profile, class_profile, guardian_profile\n"
            + "where student_profile.admission_no = class_profile.admission_no\n"
            + "and student_profile.admission_no = hostel_profile.admission_no\n"
            + "and student_profile.admission_no = guardian_profile.admission_no\n"
            + "and hostel_profile.hostel_name = \"Benue Hostel\"",
            sql_rima_hostel = "SELECT std_id, student_profile.admission_no, surname, firstname, othername, \n"
            + "dob, sex,class_profile.level,class, religion, hostel_name, floor_no, \n"
            + "guardian_name from student_profile, hostel_profile, class_profile, guardian_profile\n"
            + "where student_profile.admission_no = class_profile.admission_no\n"
            + "and student_profile.admission_no = hostel_profile.admission_no\n"
            + "and student_profile.admission_no = guardian_profile.admission_no\n"
            + "and hostel_profile.hostel_name = \"Rima Hostel\"",
            sql_watari_hostel = "SELECT std_id, student_profile.admission_no, surname, firstname, othername, \n"
            + "dob, sex,class_profile.level,class, religion, hostel_name, floor_no, \n"
            + "guardian_name from student_profile, hostel_profile, class_profile, guardian_profile\n"
            + "where student_profile.admission_no = class_profile.admission_no\n"
            + "and student_profile.admission_no = hostel_profile.admission_no\n"
            + "and student_profile.admission_no = guardian_profile.admission_no\n"
            + "and hostel_profile.hostel_name = \"Watari Hostel\"",
            sql_emotan_hostel = "SELECT std_id, student_profile.admission_no, surname, firstname, othername, \n"
            + "dob, sex,class_profile.level,class, religion, hostel_name, floor_no, \n"
            + "guardian_name from student_profile, hostel_profile, class_profile, guardian_profile\n"
            + "where student_profile.admission_no = class_profile.admission_no\n"
            + "and student_profile.admission_no = hostel_profile.admission_no\n"
            + "and student_profile.admission_no = guardian_profile.admission_no\n"
            + "and hostel_profile.hostel_name = \"Emotan Hostel\"",
            sql_amina_hostel = "SELECT std_id, student_profile.admission_no, surname, firstname, othername, \n"
            + "dob, sex,class_profile.level,class, religion, hostel_name, floor_no, \n"
            + "guardian_name from student_profile, hostel_profile, class_profile, guardian_profile\n"
            + "where student_profile.admission_no = class_profile.admission_no\n"
            + "and student_profile.admission_no = hostel_profile.admission_no\n"
            + "and student_profile.admission_no = guardian_profile.admission_no\n"
            + "and hostel_profile.hostel_name = \"Amina Hostel\"";

    private DefaultListModel<String> model;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox all_hostel;
    private javax.swing.JCheckBox boys_hostel;
    private javax.swing.JButton btn_admin;
    private javax.swing.JButton btn_gen_rep;
    private javax.swing.ButtonGroup btn_group;
    private javax.swing.JPanel btn_holders;
    private javax.swing.JButton btn_print;
    private javax.swing.JCheckBox girls_hostel;
    private javax.swing.JList hostel_list;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel report_panel;
    private javax.swing.JTable result_table;
    private TableSorter sorter;
    private MySQLAdapter db_adabter;
    // End of variables declaration//GEN-END:variables
}
